module.exports = {
  AUTH_FAIL_CACHE_KEY_PREFIX: 'shore_auth_',
  ATUH_FAIL_LIMIT_BURST: 10,
  AUTH_FAIL_LIMIT_DURATION: 24 * 60 * 60,

  YACHT_CREATE_CACHE_KEY_PREFIX: 'shore_create_',
  YACHT_CREATE_LIMIT_BURST: 20,
  YACHT_CREATE_LIMIT_DURATION: 24 * 60 * 60

};
